#!/usr/bin/env bash

set -eu

staged_files_count=$(git status --porcelain | grep -E "^(A|M) " | wc -l)
[[ $staged_files_count  == "0" ]] && echo "no file staged" && exit 1

echo -e "\e[0;30mstarting to lint...\e[0m"
npm run lint-staged
echo -e "\e[0;30mstarting to test...\e[0m"
export CONSOLE=silent; export NODE_ENV=tests; npm test > /dev/null
