#!/usr/bin/env bash

logDone(){
  echo -e '\e[0;32mdone browserifying:\e[0m' $1
}

browserify node_modules/levelup -s LevelUp > vendor/scripts/level-up.js; logDone LevelUp
browserify node_modules/level-js -s LevelJs > vendor/scripts/level-js.js ; logDone LevelJs
browserify node_modules/level-multiply -s LevelMultiply > vendor/scripts/level-multiply.js ; logDone LevelMultiply
browserify node_modules/level-promise -s LevelPromise > vendor/scripts/level-promise.js ; logDone LevelPromise
# browserify node_modules/es6-promise -s es6Promise > vendor/scripts/es6-promise.js ; logDone es6Promise
