#!/usr/bin/env bash
mkdir -p ./app/assets/js
i18n_content_hash=$(cat ./public/i18n/*.json | sha256sum | cut -c1-7)
echo "export const i18nContentHash = '${i18n_content_hash}'" > ./app/assets/js/build_metadata.js
