#!/usr/bin/env bash
PUBLIC=$(pwd)/public

# partials used to keep pieces of code not useful for development out of the index
./scripts/add_index_partials.coffee
echo 'partials added'

# Remove comments (assumes that there are no multilines comments)
sed -iE '/^\s*<!--/d' $PUBLIC/index.html
# Remove indentation spaces
sed -iE 's/^\s*//' $PUBLIC/index.html
# Remove empty lines
sed -iE '/^$/d' $PUBLIC/index.html
echo 'index.html minified'

./scripts/add_jsonld_actions.coffee
echo 'jsonld actions added'
