#!/usr/bin/env zsh
echo -e '\e[0;30mupdate_i18n_all\e[0m'
./scripts/update_i18n_all

echo -e '\e[0;30mgzip all i18n files\e[0m'
source ./scripts/init_gzip_utils
gzipkeepall public/i18n/dist

# preparing updated i18n source files for transifex
transifexify public/i18n/src/{short,full}key/en.json