#!/usr/bin/env bash

# Exit on error (cf http://jvns.ca/blog/2017/03/26/bash-quirks/)
set -e

echo -e '\e[0;30mupdating i18n\e[0m'
./scripts/build_i18n

echo -e '\e[0;30mbrunch build --production\e[0m'
brunch build --production
./scripts/build_index

echo -e '\e[0;30mgzip js, css, and font files\e[0m'
./scripts/set_content_hash_cache_bust

echo -e '\e[0;30mupdate mentions\e[0m'
./scripts/update_mentions.coffee

rm -f public/json/*.gz
gzip -9kf public/json/*.json

rm -f public/fonts/*.gz
gzip -9kf public/fonts/*

echo -e '\e[0;30mgzip index.html\e[0m'
gzip -9kf public/index.html
echo -e '\e[0;30mgzip robots.txt\e[0m'
gzip -9kf public/robots.txt

# Run once every now and then
[ "${RANDOM:0:1}" = 9 ] && {
  echo -e '\e[0;30mgenerate sitemaps\e[0m'
  npm run generate-sitemaps
}

./scripts/weight_watcher
