#!/usr/bin/env bash
PUBLIC=$(pwd)/public
# it is useful to keep piwik's code separated so that it doesn't do requests while in development
./scripts/add_piwik.coffee
echo 'piwik added'
html-minifier --collapse-whitespace --remove-comments --minify-js $PUBLIC/index.html --output $PUBLIC/index.html
echo 'index.html minified'
./scripts/add_jsonld_actions.coffee
echo 'jsonld actions added'
