#!/usr/bin/env bash

# Exit on error (cf http://jvns.ca/blog/2017/03/26/bash-quirks/)
set -e

echo -e '\e[0;30mupdating i18n\e[0m'
./scripts/build_i18n

echo -e '\e[0;30mbrunch build --production\e[0m'
brunch build --production
./scripts/build_index

echo -e '\e[0;30mgzip js, css, and font files\e[0m'
./scripts/set_content_hash_cache_bust

rm -f public/json/*.gz
gzip --best --keep public/json/*.json

rm -f public/fonts/*.gz
gzip --best --keep public/fonts/*

echo -e '\e[0;30mgzip index.html\e[0m'
gzip --best < public/index.html > public/index.html.gz
echo -e '\e[0;30mgzip robots.txt\e[0m'
gzip --best < public/robots.txt > public/robots.txt.gz

# Run once every now and then
[ "${RANDOM:0:1}" = 9 ] && {
  echo -e '\e[0;30mgenerate sitemaps\e[0m'
  npm run generate-sitemaps
}

./scripts/weight_watcher
