#!/usr/bin/env bash

# Keep 'inventaire-i18n' as the directory name to make this directory easy to ignore
# in gitignore or text editor exclude patterns

[ -e inventaire-i18n ] && {
  cd inventaire-i18n
  # Update dist files
  git fetch origin dist
  git checkout origin/dist
  git checkout -B dist
  cd ..
} || {
  git clone https://github.com/inventaire/inventaire-i18n.git --branch dist
}

mkdir -p ./public/i18n ./app/assets/js
echo "copying dist files"
cp inventaire-i18n/dist/client/* ./public/i18n

echo "copying languages_data.js to app/lib"
cp inventaire-i18n/dist/languages_data.js ./app/assets/js
sed -i 's/module.exports =/export default/' ./app/assets/js/languages_data.js
./node_modules/.bin/eslint --fix ./app/assets/js/languages_data.js
