#!/usr/bin/env bash
PUBLIC=$(pwd)/public
# partials used to keep pieces of code not useful for development out of the index
./scripts/add_index_partials.coffee
echo 'piwik added'
html-minifier --collapse-whitespace --remove-comments --minify-js $PUBLIC/index.html --output $PUBLIC/index.html
echo 'index.html minified'
./scripts/add_jsonld_actions.coffee
echo 'jsonld actions added'
