#!/usr/bin/env zsh
export gzipkeepall(){
  ext="$2"
  gzext="${ext}.gz"
  echo "path $1/*${gzext}"
  # delete all the .gz files
  # to avoid catching them in the * on the for loop selector
  rm -f $1/*${gzext} && echo "deleted $1/*${gzext}"
  # gzip and keep original files (compatible gzip 1.5)
  for f in $1/*${ext};
    do gzip --best < $f > "${f}.gz";
  done;
}
