#!/usr/bin/env zsh

export gzipkeepall(){
  # delete all the .gz files
  # to avoid catching them in the * on the for loop selector
  rm -f $1/*gz && echo "deleted $1/*gz"
  for f in $1/*; do gzip -9kf $f; done;
}
