#!/usr/bin/env bash

logDone(){
  echo -e '\e[0;32mdone browserifying:\e[0m' $1
}

# mv allow to be sure there wont be several copy conserved
# like include.js.1 include.js.2 etc
wget -q https://login.persona.org/include.js && mv include.js vendor/scripts
echo -e '\e[0;32mdone downloading:\e[0m persona include.js'

browserify node_modules/levelup -s LevelUp > vendor/scripts/level-up.js
logDone LevelUp

browserify node_modules/level-multiply -s LevelMultiply > vendor/scripts/level-multiply.js
logDone LevelMultiply

browserify node_modules/level-js -s LevelJs > vendor/scripts/level-js.js
logDone LevelJs

browserify node_modules/memdown -s MemDown > vendor/scripts/memdown.js
logDone MemDown

browserify node_modules/wikidata-sdk -s wdk > vendor/scripts/wikidata-sdk.js
logDone wdk

browserify -t coffeeify node_modules/inv-utils -s invUtils > vendor/scripts/inv-utils.js
logDone invUtils
