#!/usr/bin/env zsh

logDone(){
  echo -e '\e[0;32mdone browserifying:\e[0m' $1
}

# removing comments
rmComments(){
  uglify -s $1 -o $1
}

# avoid to rely on globally installed packages
# to ease installation
alias uglifyjs=node_modules/uglify-js/bin/uglifyjs
alias browserify=node_modules/browserify/bin/cmd.js

curl -sk https://piwik.allmende.io/piwik.js > vendor/scripts/piwik.js
echo -e '\e[0;32mdone downloading:\e[0m piwik.js'

browserify node_modules/levelup -s LevelUp > vendor/scripts/level-up.js
logDone LevelUp

browserify node_modules/level-multiply -s LevelMultiply > vendor/scripts/level-multiply.js
logDone LevelMultiply

browserify node_modules/level-js -s LevelJs > vendor/scripts/level-js.js
logDone LevelJs

browserify node_modules/to-data-url -s toDataURL > vendor/scripts/to-data-url.js
logDone toDataURL

browserify node_modules/browser-locale -s browserLocale > vendor/scripts/browser-locale.js
logDone browserLocale

browserify node_modules/enumerate-devices -s enumerateDevices > vendor/scripts/enumerate-devices.js
logDone enumerateDevices

cp node_modules/wikidata-sdk/dist/wikidata-sdk.js vendor/scripts/wikidata-sdk.js
echo -e '\e[0;32mdone copying:\e[0m' wdk

cp node_modules/inv-utils/dist/inv-utils.js vendor/scripts/inv-utils.js
echo -e '\e[0;32mdone copying:\e[0m' invUtils

cp node_modules/wikidata-lang/dist/index.js vendor/scripts/wikidata-lang.js
echo -e '\e[0;32mdone copying:\e[0m' wikidata-lang

pub=public/javascripts
source scripts/init_gzip_utils

memdown_base=memdown-1.1.2
browserify node_modules/memdown -s MemDown > ${pub}/${memdown_base}.js
uglifyjs ${pub}/${memdown_base}.js -c -m -o ${pub}/${memdown_base}.min.js 2> /dev/null
gzipkeep "${pub}/${memdown_base}.min.js"
echo -e '\e[0;32mdone browserifying and copying:\e[0m' memdown

quagga_base=quagga-0.9.2
cp node_modules/quagga/dist/quagga.js ${pub}/${quagga_base}.js
cp node_modules/quagga/dist/quagga.min.js ${pub}/${quagga_base}.min.js
gzipkeep "${pub}/${quagga_base}.min.js"
echo -e '\e[0;32mdone copying:\e[0m' quagga
