#!/usr/bin/env zsh

############ ENV ###############

# avoid to rely on globally installed packages
# to ease installation
alias uglifyjs=node_modules/uglify-js/bin/uglifyjs
alias browserify=node_modules/browserify/bin/cmd.js
pub=public/js
vendor=vendor/js
source scripts/init_gzip_utils

uglifyIt(){
  # 2>&1: redirect stderr to stdin to be able to pipe it
  # grep -v WARN: avoid showing warnings
  uglifyjs ${1}/${2}.js -c -m -o ${1}/${2}.min.js 2>&1 |grep -v WARN
}

# keep versions in sync with app/api/scripts.coffee
quagga_base=quagga-0.10.2
cropper_base=cropper-2.3.0

############ INSTALLATIONS ###############

curl -sk https://piwik.allmende.io/piwik.js > ${vendor}/piwik.js
echo -e '\e[0;32mdone downloading:\e[0m piwik.js'

cp node_modules/quagga/dist/quagga.js ${pub}/${quagga_base}.js
cp node_modules/quagga/dist/quagga.min.js ${pub}/${quagga_base}.min.js
gzipkeep "${pub}/${quagga_base}.min.js"
echo -e '\e[0;32mdone copying:\e[0m' quagga

cp node_modules/cropper/dist/cropper.css vendor/css
cp node_modules/cropper/dist/cropper.js ${pub}/${cropper_base}.js
cp node_modules/cropper/dist/cropper.min.js ${pub}/${cropper_base}.min.js
gzipkeep "${pub}/${cropper_base}.min.js"
echo -e '\e[0;32mdone copying:\e[0m' cropper
