#!/usr/bin/env sh
if [ "$1" != "" ] ; then
  eslint --config .eslintrc.cjs --format codeframe --ext js,svelte --fix "$@"
else
  eslint --config .eslintrc.cjs --format codeframe --ext js,svelte --fix app tests scripts
fi
