#!/usr/bin/env sh
if [ "$1" != "" ] ; then
  eslint --config .eslintrc.cjs --format codeframe --ext js,svelte "$@"
else
  eslint --config .eslintrc.cjs --format codeframe --ext js,svelte app tests scripts
fi
