#!/usr/bin/env sh
if [ "$1" != "" ] ; then
  eslint --config .eslintrc.cjs --format codeframe --ext js,svelte --fix "$@"
  stylelint --config .stylelintrc.cjs --fix "$@"
else
  eslint --config .eslintrc.cjs --format codeframe --ext js,svelte --fix app tests scripts
  stylelint --config .stylelintrc.cjs --fix app
fi
