#!/usr/bin/env bash

set -e

ESLINT_ARGS="--format codeframe --ext js,ts,svelte --config eslint.config.cli.js"

if [ "$1" != "" ] ; then
  eslint $ESLINT_ARGS "$@"
  stylelint --config .stylelintrc.cjs --quiet-deprecation-warnings --allow-empty-input "$@"
else
  eslint $ESLINT_ARGS app tests scripts
  stylelint --config .stylelintrc.cjs --quiet-deprecation-warnings app
fi
