#!/usr/bin/env sh

CWD=$PWD
bowerMoment=./bower_components/moment/locale
publicMoment=./public/js/moment
mkdir -p $publicMoment

cp $bowerMoment/* $publicMoment
cd $publicMoment

gzip --best *.js
cd $CWD

# add a non gziped copy for development
cp $bowerMoment/* $publicMoment
