#!/usr/bin/env bash

set -eu

CWD=$PWD
moment_local_folder=./node_modules/moment/locale
public_moment_folder=./public/js/moment
mkdir -p $public_moment_folder

cp $moment_local_folder/* $public_moment_folder
cd $public_moment_folder

gzip --best --force *.js
cd $CWD

# add a non gziped copy for development
cp -f $moment_local_folder/* $public_moment_folder
