#!/usr/bin/env bash
./scripts/slim_packages.coffee
./scripts/install_scripts
bower install
./scripts/bower_fix.coffee
../scripts/run_patches $HOME/inventaire/client/scripts/patches
./scripts/mv_font_awesome_fonts
./scripts/mv_moment_locales

# need to build once to make the public folder available
./node_modules/brunch/bin/brunch build

git clone -b i18n git@github.com:maxlath/inventaire-client.git ./public/i18n
mkdir -p ./server/lib/emails/i18n/dist
./scripts/update_i18n_all
