#!/usr/bin/env bash

mkdir -p ./public/json
cp -r app/assets/* ./public

npm run update-mentions
./scripts/build_i18n

# Make git hooks trackable (see https://stackoverflow.com/a/4457124/3324977)
rm -rf .git/hooks
ln -s .githooks .git/hooks

curl -sk https://piwik.allmende.io/piwik.js > ./vendor/piwik.js
