#!/usr/bin/env bash
[[ -e /tmp/client_patches_history ]] || git log --patch > /tmp/client_patches_history

# Find strings that aren't used anymore
# but that were used in the past, and that were thus either deleted or changed to a computed string

# NB: in case this removes the last entry in a file, you might end up having to manually
# remove the last entry's comma, as JSON doesn't like that extra comma.

find_and_delete(){
  file_path=$1
  cat "$file_path" | \
    jq -r 'keys | .[]' | \
    while read -r line; do
      grep "$line" public/js/app.js scripts/assets/missing_i18n_strings_ignorelist > /dev/null || {
        # Rulling-out computed strings such as 'saving would create a new ${type}'
        grep "$line" /tmp/client_patches_history > /dev/null && {
          echo "deleted: $line"
          sed -i "/$line/d" "$file_path"
        }
      }
    done
}

find_and_delete inventaire-i18n/original/fullkey.en.json
find_and_delete inventaire-i18n/original/shortkey.en.json

