#!/usr/bin/env sh

# A script to cache-bust files by content hash
# to allow to serve those files with immutable cache rules

get_content_hash(){
  md5sum "$1" | awk '{print $1}' | cut -c 1-7
}

create_content_hash_copies(){
  content_hash=$(get_content_hash "$1.$2")
  # Copy file
  cp "$1.$2" "$1.$content_hash.$2"
  # Copy associated map file
  cp "$1.$2.map" "$1.$content_hash.$2.map"
  # Gzip those new files
  gzip -9fk "$1.$content_hash.$2" "$1.$content_hash.$2.map"
  # Update index.html with the new file paths
  sed -i "s@$1.$2@$1.$content_hash.$2@" public/index.html
}

create_content_hash_copies public/js/app js
create_content_hash_copies public/js/vendor js
create_content_hash_copies public/css/app css
create_content_hash_copies public/css/vendor css
