#!/usr/bin/env sh
# keep an history if builds weight
PWD=$(pwd)
FOLDER="$PWD/scripts/assets/weight_history"
JS="$PWD/public/js"
CSS="$PWD/public/css"

COMMIT=$(git rev-parse --short HEAD)
DATE=$(git show -s --format="%ci" $COMMIT|sed 's/ .*$//')
FILE="$FOLDER/$DATE-$COMMIT"

echo "-- date: $DATE - commit: $COMMIT --" > $FILE

cd $JS
du -s -h app.js >> $FILE
du -s -h app.js.gz >> $FILE
du -s -h vendor.js >> $FILE
du -s -h vendor.js.gz >> $FILE
cd $CSS
du -s -h app.css >> $FILE
du -s -h app.css.gz >> $FILE
du -s -h vendor.css >> $FILE
du -s -h vendor.css.gz >> $FILE
cat $FOLDER/* | tail -n 20
